name: peopleco
favicon: null
layout_spectrum: 0.036575669422745705
typography_spectrum: 0.4367516974452883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8379fc'
    - '#e2a880'
    - '#ff70fe'
    - '#f15a4f'
  brandStrength: 0.5
  lightness: 0.40074071916751564
  saturation: 0.6132423479575664
  rhythmicContrast: 0.7635444493498653
purpose: []
